[package]
name = "taskn"
version = "0.1.0"
authors = ["Cerek Hillen <cerekh@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.19"
lazy_static = "1.4.0"
serde = { version = "1.0.123", features = ["derive"] }
serde_json = "1.0.61"
shellexpand = "2.1.0"
structopt = "0.3.21"
